use nixpkgs.1809.darwin channel
# what went wrong:
nixops has problems with IN_NIX_SHELL being set.
error: a 'x86_64-linux' is required to build '/nix/store/azxx0j65b6pqwih6yaa5dzpiri8l9r4c-linux-4.14.83.drv', but I am a 'x86_64-darwin'